#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: project-ember-seed.sh <print|apply>

Commands:
  print  Emit the SQL needed to seed a local smoke-test user and realm.
  apply  Emit the SQL and apply it to the login database with mysql.

Environment:
  EMBER_BUILD_DIR          CMake build directory. Default: build/openclaw-vcpkg
  EMBER_DB_HOST            MySQL host. Default: 127.0.0.1
  EMBER_DB_PORT            MySQL port. Default: 3306
  EMBER_LOGIN_DB           Login DB name. Default: ember_login
  EMBER_LOGIN_DB_USER      Login service DB user. Default: ember_login
  EMBER_LOGIN_DB_PASSWORD  Login service DB password. Default: ember_login
  MYSQL_CLIENT             mysql-compatible client. Default: mysql
  EMBER_DEFAULT_USER       Smoke account username. Default: OPENCLAW
  EMBER_DEFAULT_PASS       Smoke account password. Default: openclaw
  EMBER_DEFAULT_EMAIL      Smoke account email. Default: openclaw@example.invalid
  EMBER_REALM_ID           Realm id to upsert. Default: 1
  EMBER_REALM_NAME         Realm name. Default: Ember Local
  EMBER_REALM_IP           Realm IP advertised to the client. Default: 127.0.0.1
  EMBER_REALM_PORT         Realm port advertised to the client. Default: 8085
  EMBER_REALM_TYPE         Realm type. Default: 1
  EMBER_REALM_FLAGS        Realm flags. Default: 0
  EMBER_REALM_POPULATION   Realm population. Default: 0
  EMBER_REALM_CREATION     Realm creation setting. Default: 0
  EMBER_REALM_CATEGORY     Realm category. Default: 1
  EMBER_REALM_REGION       Realm region. Default: 3
USAGE
}

die() {
  echo "error: $*" >&2
  exit 1
}

repo_root() {
  local script_dir
  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  cd -- "${script_dir}/../.." && pwd
}

abs_path() {
  local value="$1"
  local base="$2"
  if [[ "${value}" = /* ]]; then
    printf '%s\n' "${value}"
  else
    printf '%s/%s\n' "${base}" "${value}"
  fi
}

json_string() {
  local data="$1"
  local key="$2"
  python3 -c 'import json, sys; print(json.load(sys.stdin)[sys.argv[1]])' "${key}" <<<"${data}"
}

hex_literal() {
  local value="$1"
  value="${value#0x}"
  value="${value#0X}"
  [[ "${value}" =~ ^[0-9a-fA-F]+$ ]] || die "expected hex value, got: ${value}"
  printf '%s' "${value}"
}

sql_escape() {
  python3 -c "import sys; print(sys.stdin.read().replace('\\\\', '\\\\\\\\').replace(\"'\", \"''\"), end='')"
}

sql_value() {
  local value="$1"
  local escaped
  escaped="$(sql_escape <<<"${value}")"
  printf "'%s'" "${escaped}"
}

number_value() {
  local value="$1"
  [[ "${value}" =~ ^[0-9]+([.][0-9]+)?$ ]] || die "expected numeric value, got: ${value}"
  printf '%s' "${value}"
}

seed_sql() {
  local root="$1"
  local build_dir="$2"
  local srpgen="${build_dir}/src/tools/srpgen/srpgen"

  [[ -x "${srpgen}" ]] || die "missing srpgen executable: ${srpgen}"

  local account_json username verifier salt
  account_json="$("${srpgen}" --json --username "${EMBER_DEFAULT_USER:-OPENCLAW}" --password "${EMBER_DEFAULT_PASS:-openclaw}")"
  username="$(json_string "${account_json}" username)"
  verifier="$(json_string "${account_json}" verifier)"
  salt="$(hex_literal "$(json_string "${account_json}" salt)")"

  local email realm_id realm_name realm_ip realm_port realm_type realm_flags
  local realm_population realm_creation realm_category realm_region
  email="${EMBER_DEFAULT_EMAIL:-openclaw@example.invalid}"
  realm_id="${EMBER_REALM_ID:-1}"
  realm_name="${EMBER_REALM_NAME:-Ember Local}"
  realm_ip="${EMBER_REALM_IP:-127.0.0.1}"
  realm_port="${EMBER_REALM_PORT:-8085}"
  realm_type="${EMBER_REALM_TYPE:-1}"
  realm_flags="${EMBER_REALM_FLAGS:-0}"
  realm_population="${EMBER_REALM_POPULATION:-0}"
  realm_creation="${EMBER_REALM_CREATION:-0}"
  realm_category="${EMBER_REALM_CATEGORY:-1}"
  realm_region="${EMBER_REALM_REGION:-3}"

  cat <<SQL
-- Generated by scripts/openclaw/project-ember-seed.sh from ${root}
INSERT INTO users
  (username, s, v, creation_date, email, verified, subscriber, survey_request, pin_method, pin, totp_key)
VALUES
  ($(sql_value "${username}"), X'${salt}', $(sql_value "${verifier}"), UTC_TIMESTAMP, $(sql_value "${email}"),
   b'1', b'1', b'0', 0, NULL, NULL)
ON DUPLICATE KEY UPDATE
  s = VALUES(s),
  v = VALUES(v),
  email = VALUES(email),
  verified = VALUES(verified),
  subscriber = VALUES(subscriber),
  survey_request = VALUES(survey_request),
  pin_method = VALUES(pin_method),
  pin = VALUES(pin),
  totp_key = VALUES(totp_key);

INSERT INTO realms
  (id, name, ip, type, flags, population, creation_setting, category, region, port)
VALUES
  ($(number_value "${realm_id}"), $(sql_value "${realm_name}"), $(sql_value "${realm_ip}"),
   $(number_value "${realm_type}"), $(number_value "${realm_flags}"), $(number_value "${realm_population}"),
   $(number_value "${realm_creation}"), $(number_value "${realm_category}"), $(number_value "${realm_region}"),
   $(number_value "${realm_port}"))
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  ip = VALUES(ip),
  type = VALUES(type),
  flags = VALUES(flags),
  population = VALUES(population),
  creation_setting = VALUES(creation_setting),
  category = VALUES(category),
  region = VALUES(region),
  port = VALUES(port);
SQL
}

apply_sql() {
  local sql="$1"
  local client="${MYSQL_CLIENT:-mysql}"
  command -v "${client}" >/dev/null 2>&1 || die "missing mysql client: ${client}"

  local cnf_file
  cnf_file="$(mktemp)"
  chmod 0600 "${cnf_file}"
  trap 'rm -f "${cnf_file}"' EXIT

  cat >"${cnf_file}" <<EOF
[client]
user=${EMBER_LOGIN_DB_USER:-ember_login}
password=${EMBER_LOGIN_DB_PASSWORD:-ember_login}
host=${EMBER_DB_HOST:-127.0.0.1}
port=${EMBER_DB_PORT:-3306}
EOF

  "${client}" --defaults-extra-file="${cnf_file}" "${EMBER_LOGIN_DB:-ember_login}" <<<"${sql}"
}

main() {
  local command="${1:-}"
  if [[ -z "${command}" || "${command}" == "-h" || "${command}" == "--help" ]]; then
    usage
    exit 0
  fi

  local root build_dir sql
  root="$(repo_root)"
  build_dir="$(abs_path "${EMBER_BUILD_DIR:-build/openclaw-vcpkg}" "${root}")"
  sql="$(seed_sql "${root}" "${build_dir}")"

  case "${command}" in
    print)
      printf '%s\n' "${sql}"
      ;;
    apply)
      printf '%s\n' "${sql}"
      apply_sql "${sql}"
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
}

main "$@"
